## Postgres
development:
  adapter: postgresql
  host: localhost
  database: monologue_development
  username: postgres

test:
  adapter: postgresql
  host: localhost
  database: monologue_test
  username: postgres
