## Postgres
development:
  adapter: postgresql
  host: localhost
  database: tmp_development
  username: postgres

test:
  adapter: postgresql
  host: localhost
  database: tmp_test
  username: postgres